WordPress/Requests

- examples/cookie.php
Took me a little while to figure out how to use Cookies in the request so I though I would contribute an example
> Added example on how to use Cookie

- examples/cookie_jar.php
As requested by @rmccue in #124
> Added Request_Cookie_Jar example

- library/Requests/Transport/fsockopen.php
> Remove duplicated stream_get_meta_data call

- library/Requests/Transport/fsockopen.php
This will enable more accurate error handling
> Transmits $errno from stream_socket_client in exception

- .travis.yml
> Ensure our Heroku instance is awake

- README.md
We've currently got the old PNG there, eww. Let's update to SVG and move to the top.
> Update Build Status image

- library/Requests.php
- library/Requests/Cookie.php
- library/Requests/Cookie/Jar.php
- library/Requests/Session.php
- tests/Session.php
- tests/Transport/Base.php
- tests/phpunit.xml.dist
Improving the unit tests, one line at a time.
> Improve our tests (yay)

- docs/hooks.md
- library/Requests/Transport/cURL.php
- library/Requests/Transport/fsockopen.php
- tests/Transport/Base.php
> Pass cURL info to after_request

- library/Requests/Transport/fsockopen.php
Props @amandato from https://core.trac.wordpress.org/ticket/37992
> Respect port if specified for HTTPS connections

- library/Requests/IRI.php
- tests/IRI.php
> Allow paths starting with a double-slash

- .travis.yml
- tests/Transport/Base.php
- tests/bootstrap.php
- tests/phpunit6-compat.php
- tests/utils/proxy/proxy.py
This PR combines the effort from #298, #280, and #302 and fixes the final few issues affecting the build.
For the background on what this PR actually contains, please see https://github.com/rmccue/Requests/pull/302#issuecomment-351053054
> Fix Travis CI (Take 4)

- library/Requests/SSL.php
This changes "blacklisted" to "blocklisted". It is more clear and more inclusive language.
> Use more clear and inclusive language.

- library/Requests/Cookie.php
- library/Requests/Cookie/Jar.php
- library/Requests/IRI.php
- library/Requests/Response/Headers.php
- library/Requests/Transport/cURL.php
- library/Requests/Transport/fsockopen.php
- library/Requests/Utility/CaseInsensitiveDictionary.php
> Nits on phpdoc, use of internal methods with unexpected type

- library/Requests/IPv6.php
_[This PR is part of a series to introduce code style checking to the repo]_
> CS: use `elseif` not `else if`

- library/Requests/Utility/FilteredIterator.php
- tests/Utility/FilteredIterator.php
This is just an extension of #421 with some tests from WordPress core.
> Tests added for #421

- library/Requests/IDNAEncoder.php
- library/Requests/Response.php
- library/Requests/Session.php
- library/Requests/Transport/fsockopen.php
- tests/Cookies.php
- tests/Transport/Base.php
* No inline tabs.
* Remove commented out code.
* Minor comment fixes.
(last one before I can pull the ruleset :tada: )
> CS: miscellaneous fixes

- docs/authentication-custom.md
- docs/authentication.md
- docs/goals.md
- docs/hooks.md
- docs/proxy.md
- docs/usage-advanced.md
- docs/usage.md
- docs/why-requests.md
Fixes #442.
Add pagination to documentation pages.
> Add pagination to documentation pages

- _layouts/documentation.html
- _layouts/home.html
- _layouts/page.html
- docs/index.md
- index.md
* Update footer link for Ryan's website.
* Update own links from http to https
Sister-PR to #481
> GH Pages: update some links

- .github/release-checklist.md
... to document the release process and as a reminder for the future.
> Add a release checklist

- tests/Transport/BaseTestCase.php
> Add tests for 303 status code
