WordPress/Requests

.gitignore
Just a simple fix to get a cleaner `git status` without the gazillion coverage files
=> Ignore coverage report files

library/Requests.php
Updated exception message for when url does not conform to HTTP or
HTTPS to clarify that both HTTP and HTTPS requests are handled.
#161
=> Updated exception message to specify both http + https

library/Requests/Transport/cURL.php
=> Sets `stream_headers` method to public to allow calling it from other places.

library/Requests.php, library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php, tests/Transport/Base.php
Continues @ozh's PR from #147, but with master merged so the tests are running up-to-date.
=> Add byte limit option

library/Requests.php, library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php
This PR allows to fetch the XXX first bytes of a remote URL
Changes:
* New option: `response_byte_limit` to limit response body (integer | false)
* New constant: `CHUNK`, used to define the buffer chunk size, that was hardcoded in the socket transport class as 1160 and is now used also in the cURL class
* New test that passes with both transport
Key concept with cURL:
```php
<?php
$url  = 'http://httpbin.org/';
$html ='';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,$url);
// These 3 settings
curl_setopt($ch, CURLOPT_BUFFERSIZE, 10); // smaller chunks = more progress checks
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_WRITEFUNCTION, 'write_function');
// callback : returns either strlen of data read (and continues) or 0 and halts with an error
function …
```
=> Allow size limit of data read

.travis.yml, library/Requests/IRI.php, library/Requests/Transport/cURL.php
Looks like we're accidentally using `CURLOPT_FILE` still, but it was obsoleted by #147/#172.
There might be further problems too.
Fixes #171.
=> Fix PHP 7 compatibility

.travis.yml
=> Switch to new Travis infrastructure

tests/bootstrap.php
I've set up a Heroku instance of the test server at https://requests-php-tests.herokuapp.com/ so we can stop having broken tests by default :)
Fixes #139
=> Use Heroku instance for tests by default

library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php, tests/Transport/Base.php
=> Add progress hook

library/Requests/Cookie.php, library/Requests/Cookie/Jar.php, tests/Cookies.php
=> Actually check cookie expirations

tests/Transport/Base.php
This replaces tv.eurosport.com, which I've never liked, although it is used in other test suites. badssl.com is specifically for SSL testing, and is used in Chrome to test SSL.
=> Use wrong.host.badssl.com for SSL domain check test

library/Requests/Cookie.php, library/Requests/Cookie/Jar.php, tests/Cookies.php
Accidentally introduced a bunch of semiCamelCase methods in #130, whoops.
=> Correct methods to use snake_case

library/Requests.php, library/Requests/Auth/Basic.php, library/Requests/Cookie.php, library/Requests/Cookie/Jar.php, library/Requests/Exception/HTTP.php, library/Requests/Exception/HTTP/304.php, library/Requests/Exception/HTTP/305.php, library/Requests/Exception/HTTP/306.php, library/Requests/Exception/HTTP/Unknown.php, library/Requests/Hooks.php, library/Requests/IDNAEncoder.php, library/Requests/IPv6.php, library/Requests/IRI.php, library/Requests/Proxy/HTTP.php, library/Requests/Response.php, library/Requests/Response/Headers.php, library/Requests/SSL.php, library/Requests/Session.php, library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php, library/Requests/Utility/CaseInsensitiveDictionary.php, library/Requests/Utility/FilteredIterator.php, tests/Transport/Base.php
Let's improve quality based on Scrutinizer reports.
=> Improve code quality

.gitignore, library/Requests.php, library/Requests/Response.php, library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php, library/Requests/Utility/CaseInsensitiveDictionary.php, tests/Requests.php, tests/Transport/Base.php
Following on from @egeloen's fantastic work in #143, this merges master in and corrects some small issues.
Fixes #137, fixes #91.
=> Fix/Rationalize transports (v2)

tests/Transport/Base.php
=> Remove sni.velox.ch from the test suite

.travis.yml, tests/Transport/Base.php, tests/utils/proxy/proxy.py
mitmproxy changed the format for scripts, and we're just using the latest, so the tests are now broken. This updates to the latest and corrects the script, but fixes it at this version to avoid this in the future.
=> Fix tests (mitmproxy error)

library/Requests/Exception/Transport.php, library/Requests/Exception/Transport/cURL.php, library/Requests/Transport/cURL.php
This is a work in progress, but I wanted to get comments sooner rather than later, since this is mostly complete.
I have a couple use cases involved here:
1. I have a need to detect different kinds of cURL errors from multi-requests, specifically CURLE_OPERATION_TIMEDOUT (28), since I have subrequests using timeouts.  These currently manifest as 'requests.no_crlf_separator' due to nothing being returned from curl_multi_getcontent in request_multiple resulting in a parse error.  These are detectable from the code in $done['code'], but none of this is exposed anywhere I can get to.
1. I want to be able to capture the time when an error has finished, and have the code available there.  I've added this as a separate hook to not break existing parse_response implementations, but I'm open to …
=> RFC / WIP (do not merge): surface cURL errors

library/Requests.php
This allows implementing things like browser-compatible redirect handling:
```
$hooks->register( 'requests-requests.before_redirect', function ( $location, $headers, $data, &$options, $original ) {
// Browser compat
if ( $original->status_code === 301 || $original->status_code === 302 ) {
$options['type'] = Requests::GET;
}
});
```
Fixes #201, see #178.
=> Add a before_redirect hook to alter redirects

library/Requests/Transport/cURL.php
Curl spammed the file descriptor list with CLOSE_WAIT connections and the Requests_Transport_cURL Instances where never actually destroyed because of a $this reference in the curl handle.
This resulted in a memleak and failing requests after a few 100 being made.
I fixed this by removing the reference from the file handle again after each request.
=> Fix for memleak and curl_close() never being called

library/Requests.php
Easy fix to improve usability. :) Fixes #204.
=> Uppercase the method to ensure compatibility

library/Requests.php
If you're embedding Requests into an existing framework, you may want to bundle your own certificates. This allows you to deduplicate the certificates without causing direct use of Requests to fail.
=> Store default certificate path

library/Requests/Transport/cURL.php
cURL <7.22 seems to hold the request open if the connection is
keep-alive and the buffer hasn't been filled. Changing to single
connections is slightly less efficient (although unnoticable in most
uses), but should fix this issue.
If you need keep-alive, set the Connection header manually.
=> Force closing keep-alive connections on old cURL

library/Requests/Exception/HTTP/418.php, library/Requests/Exception/HTTP/428.php, library/Requests/Exception/HTTP/429.php, library/Requests/Exception/HTTP/431.php, library/Requests/Exception/HTTP/511.php, library/Requests/IDNAEncoder.php, library/Requests/SSL.php, library/Requests/Session.php, library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php
I mistakenly let these changes slip into WordPress via [r37674](https://core.trac.wordpress.org/changeset/37674), so this PR brings those same changes here to Requests.
=> Docs: Updated HTTP links with HTTPS links where applicable

library/Requests.php, library/Requests/Transport/cURL.php
cURL sucks, `getaddrinfo` sucks, and everything in general sucks.
=> Round up to at least 1 second timeouts for cURL

library/Requests.php, tests/Proxy/HTTP.php
See https://core.trac.wordpress.org/attachment/ticket/37107/37107.diff and https://github.com/rmccue/Requests/blob/2781cddf860322d5441362faf08ebc533619dbcd/library/Requests.php#L325-L326.
=> Support a Requests_Proxy_HTTP() instance for the proxy setting.

library/Requests/Transport/cURL.php, tests/Transport/Base.php
See https://core.trac.wordpress.org/ticket/37503 for background.
The test doesn't work (yet) because there is no /purge endpoint.
=> cURL: Support custom HTTP methods

library/Requests/Transport/cURL.php
Some hosts disable cURL by adding `disable_functions = curl_exec` to their `php.ini` file without also adding `curl_init` to the same declaration.
Request's logic appears incorrect here, bailing only if BOTH `curl_init()` AND `curl_exec()` are disabled.
=> Bail from cURL when either `curl_init()` OR `curl_exec()` are unavailable

library/Requests/Transport/fsockopen.php
Even with `verify_peer` disabled, OpensSSL will still perform peer_name checking, for example:
```
stream_socket_client(): Peer certificate CN=`dev.dd32.id.au' did not match expected CN=`test-vm'
stream_socket_client(): Failed to enable crypto
stream_socket_client(): unable to connect to ssl://test-vm:8443 (Unknown error)
```
=> Disable OpenSSL's internal peer_name checking when `verifyname` is disabled.

library/Requests/Transport/fsockopen.php
Based on @amandato in https://core.trac.wordpress.org/ticket/37991
=> Only include the port number in the `Host` header when it differs from default

library/Requests.php, tests/ChunkedEncoding.php
A chunk size must be followed by either optional chunk extension(s) (which begin with a semicolon) or \r\n. The current implementation just allows anything from the chunk size to the \r\n.
This was causing a bug in my [Events](http://wordpress.org/plugins/event-organiser/) plugin: a Google iCal feed was *sometimes* mistaken for being chunked (Google claims it is in the header: it isn't).
The starting line is 
```
BEGIN:VCALENDAR
```
which is mistakenly interpreted as a chunk header with size `BE`. *If*, it just so happens the rest of the feed is interpreted as chunked you end up with a mutilated iCal feed.
Of course, Google shouldn't claim it is chunked, but the current implementation fails to detect that it is not a valid encoding.
=> Fixes bug in rfc2616 #3.6.1 implementation.

library/Requests.php, library/Requests/Transport/cURL.php
If give a empty array to CURLOPT_HTTPHEADER, the PHP will crash.
=> CURLOPT_HTTPHEADER在php7接受空数组导致php-fpm奔溃

library/Requests/Transport/cURL.php
Fixes a "cannot access protected method Requests_Transport_cURL::stream_body()" error when using PHPUnit and PHP-VCR.
Related issues: #157 and php-vcr/php-vcr#109
=> Make Requests_Transport_cURL::stream_body() public

.travis.yml, tests/Transport/Base.php, tests/bootstrap.php, tests/phpunit6-compat.php
This is a WIP to fix Travis CI - ~Do Not Merge Yet~ 🤖 
Cherry picking various pieces from #298 and #280
=> Fix Travis CI

.travis.yml, composer.json, tests/Transport/Base.php
feelingrestful.com was decommissioned.
This should 🤞 fix the tests and allow other PRs to be merged.
=> Fix unit tests by updating domain and PHPUnit versions

library/Requests/Transport/fsockopen.php
This should fix #335.
Rather than using `%f`, this should use the non-locale aware `%F`. That way PHP will always use a period (`.`) for the decimal separator in the HTTP version, and never fallback to a comma (`,`).
I wasn’t sure how to add a test for this, as I’d want to intercept the socket message somehow. But to illustrate the issue:
```
php > echo setlocale(LC_NUMERIC, 0);
C
php > echo sprintf("%s %s HTTP/%.1f\r\n", 'GET', '/', 1.1);
GET / HTTP/1.1
php > echo setlocale(LC_NUMERIC, 'de_DE');
de_DE
php > echo sprintf("%s %s HTTP/%.1f\r\n", 'GET', '/', 1.1);
GET / HTTP/1,1
php > echo sprintf("%s %s HTTP/%.1F\r\n", 'GET', '/', 1.1);
GET / HTTP/1.1
```
=> Ignore locale when creating the HTTP version string from a float

library/Requests/Transport/fsockopen.php
`implode()` takes two parameters, `$glue` and `$pieces`.
For historical reasons, `implode()` accepted these parameters in either order, though it was recommended to use the documented argument order of `implode( $glue, $pieces )`.
PHP 7.4 is slated to deprecate the tolerance for passing the parameters for `implode()` in reverse order.
PHP 8.0 is expected to remove the tolerance for this completely.
Refs:
* https://wiki.php.net/rfc/deprecations_php_7_4#implode_parameter_order_mix
* https://php.net/manual/en/function.implode.php
=> PHP 7.4 compatibility fix / implode argument order

.travis.yml
As `Request` is supposed to work cross-version, testing against PHP 7.3 (out since dec 2018) and PHP 7.4 (expected end of november 2019) would be a good idea.
=> Travis: test against PHP 7.3 and 7.4

.travis.yml
The switch to containers via `sudo` is no longer supported by Travis.
See: https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
=> Travis: remove `sudo: false`

tests/Transport/Base.php, tests/phpunit.xml.dist
The `testAlternatePort` tests for both Curl as well as fsockopen often time out and cause builds to fail.
This PR attempts to make the builds more stable, by:
1. Retrying the request a second time if the first request timed out.
2. Skipping the unit test if the second request timed out as well.
Adding `verbose=true` to the PHPUnit config will make sure that if the tests are skipped, the skip reason will always be displayed when running the tests.
=> Unit tests: attempt to make the build more stable

.travis.yml
* Turn off Xdebug.
Xdebug is only _needed_ when code coverage is being checked. Disabling it when it's not needed, will make the Composer install a lot faster.
* Only let PHPUnit generate code coverage information when it will actually be used - i.e. in the build with `TEST_COVERAGE = 1` -.
This should make all affected builds a little faster.
=> Travis: faster builds / only generate code coverage when needed

docs/why-requests.md
Refresh of PR #334
Source: https://wordpress.org/about/stats/
Props: @tnorthcutt
=> Docs: Update stats on PHP 5.2 usage as of September 2019

.travis.yml
This PR adds linting of the PHP files in the repo against every supported PHP version to the Travis build.
The `vendor` directory is excluded by default.
For PHP 5.2, the `tests/phpunit6-compat.php` file is excluded as it uses namespaces and is only loaded on PHP 7+ anyway.
For PHP < 5.4, the `examples/cookie_jar.php` file is excluded as it uses short arrays.
=> QA: lint PHP files in this repo

examples/basic-auth.php, examples/cookie.php, examples/cookie_jar.php, examples/get.php, examples/multiple.php, examples/post.php, examples/proxy.php, examples/session.php, examples/timeout.php, library/Requests.php, tests/bootstrap.php
_[This PR is part of a series to introduce code style checking to the repo]_
`include` and `require` are language constructs, not functions.
With that in mind there are a number of best practices surrounding them:
* There is no need to use parenthesis and not doing so will be, albeit marginally, faster.
* Always pass an absolute path for maximum portability.
Using `dirname(__FILE__)` instead of `__DIR__` to maintain compatibility with PHP 5.2.
* Use `require_once` instead of `include` when the file is _required_ for the rest of the script to be able to function.
=> CS: review of all include and require statements

library/Requests/Cookie.php, tests/Cookies.php
PHP 7.4 introduces a "Trying to access array offset on value of type ..." warning for accessing null/bool/int/float/resource (everything but array, string and object) as if it were an array.
Fixes #369
=> handle no domain in a PHP7.4 compatable way

.travis.yml
1. The `trusty` environment is no longer supported. The default distro is now `xenial`.
Switching over is a good idea as the PHP `nightly` version used on `trusty` is from last January, so is not representative of PHP 8.
2. `matrix` has been renamed `jobs`, so let's use that name.
3. A lot of repos have been seeing issues with `peer fingerprint` mismatches for calls to Packagist. Prefixing the `composer install/require/remove` etc command with `travis_retry` gets round that in most cases.
=> Travis: various fixes

docs/authentication-custom.md, library/Requests/Auth.php, library/Requests/Auth/Basic.php, library/Requests/Cookie/Jar.php, library/Requests/IRI.php, library/Requests/Proxy.php, library/Requests/Proxy/HTTP.php, library/Requests/Transport/cURL.php
Objects are always passed by reference since PHP 5.0, so when a method contains typehint for a parameter saying it expects an object of a certain type, declaring that parameter as a reference is unnecessary.
Objects are always passed by reference since PHP 5.0, so passing `$this` by reference is an unnecessary PHP-4 practice.
--- 
Note: these commits _may_ (or may not) prevent some potential issue on PHP 8, but either way, they don't do any harm.
=> QA: remove unnecessary references

library/Requests.php
I'm a little aghast that nobody has come across this before and that no bug reports have come in about this (or maybe they have, but I haven't identified them as such), but the code as was, was not cross-version compatible with PHP 5 vs PHP 7 due to the [Uniform Variable Syntax](https://wiki.php.net/rfc/uniform_variable_syntax) introduced in PHP 7.0.
A detailed code sample demonstrating the issue can be found here: https://3v4l.org/T3MDQ
The current fix maintains the pre-PHP 7.0 behaviour, which I believe, as this is an older codebase, is the intended behaviour.
=> Fix PHP cross-version compatibility issue (PHP 7)

tests/phpunit.xml.dist
Looks like these have never run as they weren't included in any of the testsuites.
=> Tests: enable the `Encoding` tests

tests/Transport/Base.php
_[This PR is part of a series to introduce code style checking to the repo]_
This test should work fine without the `var_dump()`.
=> CS: remove stray debug code

library/Requests/IDNAEncoder.php
_[This PR is part of a series to introduce code style checking to the repo]_
Use PHP native comment style, rather than Perl comment style and align the start of the comments with the code.
=> CS: fix up comment indentation and style

tests/phpunit6-compat.php
Looks like this code is never used anywhere and it causes issues with PHPUnit cross-version compatibility as the `PHPUnit\Util\Test` class has become `final`.
=> QA: remove dead code

library/Requests/Transport/fsockopen.php, tests/Transport/Base.php
=> verify => false does not work with fsockopen

bin/create_pear_package.php, examples/session.php, library/Requests.php, library/Requests/Cookie.php, library/Requests/Cookie/Jar.php, library/Requests/Exception/Transport/cURL.php, library/Requests/IDNAEncoder.php, library/Requests/IPv6.php, library/Requests/Proxy/HTTP.php, library/Requests/SSL.php, library/Requests/Session.php, library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php, library/Requests/Utility/CaseInsensitiveDictionary.php, tests/Auth/Basic.php, tests/ChunkedEncoding.php, tests/Cookies.php, tests/Encoding.php, tests/IDNAEncoder.php, tests/Proxy/HTTP.php, tests/Requests.php, tests/Response/Headers.php, tests/Session.php, tests/Transport/Base.php, tests/bootstrap.php
When several lines containing assignments directly follow each other, it increases readability for the assignment operator - `=` and its variants - to be aligned.
=> CS: align multiple subsequent assignment statements

library/Requests/IDNAEncoder.php, library/Requests/Transport/cURL.php
Efficiency fix.
Don't use `count()` in a looping condition as it will be called on every single loop, while the return value of the call to `count()` should not (and doesn't in these cases) change within the loop.
=> QA: don't use count() in a looping condition

library/Requests/SSL.php
Neither `$parts` nor `$wildcard` are used in the function.
=> QA: remove unused code

library/Requests/IDNAEncoder.php
... as they can really confuse things with operator precedence.
=> CS: don't use in/decrementors within comparisons

library/Requests/Transport/fsockopen.php, tests/Transport/Base.php, tests/Transport/fsockopen.php
This PR consolidates the work done by @dd32 in PR #249 and @soulseekah in PR #318 which both addressed the same issue.
Fixes #248
Closes #249
Closes #318
=> Add Content-* headers for empty POST requests

library/Requests/IDNAEncoder.php, library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php
Multiple assignments in one statement makes for harder to debug, harder to read code and is considered a code smell.
=> CS: no multiple assignments in one statement

library/Requests.php, library/Requests/Proxy/HTTP.php, library/Requests/Response.php, library/Requests/Transport/fsockopen.php
Strict type comparisons should be used as a rule, with loose type comparisons being the exception.
This is especially important when comparing variables which are expected to be strings, as when one of the two operands - for whatever reason - is not a string, the other operand will be juggled to the type of the first operand which can lead to unexpected results and hard to debug bugs.
For array functions which do loose type comparisons, setting the third `$strict` parameter to `false` can be seen as a clear indication that this is a conscious, well thought out decision by the developer.
In all other cases, `$strict` `true` should be used.
Refs:
* http://phpcheatsheets.com/compare/equal/
* http://php.net/manual/en/function.in-array.php
=> QA: use strict comparisons

library/Requests.php
Use self when referencing a (static) class member from within the same class.
=> CS: use `self` where appropriate

library/Requests.php
Assignments in conditions makes for hard to debug, hard to read code and is considered a code smell.
=> CS: don't use assignments in conditions

tests/Auth/Basic.php, tests/IDNAEncoder.php, tests/Proxy/HTTP.php, tests/Requests.php, tests/Transport/Base.php, tests/Transport/fsockopen.php
No need to declare a variable here if it's not used other than to be `return`ed.
Each of these is testing that the function call triggers an exception - which stops the test dead - or is checking an assertion via a hooked-in method.
So no need to assign the return of the function call to a variable, when the variable is not being tested via an assertion.
=> QA: remove useless variable assignments

tests/Auth/Basic.php, tests/Cookies.php, tests/IDNAEncoder.php, tests/Proxy/HTTP.php, tests/Requests.php, tests/Response/Headers.php, tests/Transport/Base.php, tests/Transport/cURL.php, tests/Transport/fsockopen.php
Don't just verify that an exception is thrown, but verify that it is the exception expected for a particular test.
This addresses all exceptions, safe one.
Note: in some cases, the verification is done on a _partial_ message string to allow for changed exception message strings across PHP versions.
In a future commit in which the annotations for exception expectations are replaced by method calls, logic can be added to improve the message checking in a cross-version compatible manner.
=> Tests: verify exception messages

library/Requests.php
.. as that is the standard used throughout the repo.
As this is a function local variable, it can be safely renamed without consequence.
Once PHP 8 comes out, this rename would no longer be possible without causing a BC-break due to the new "named parameters in function calls" feature in PHP 8.0.
=> CS: rename a local variable to snake_case

library/Requests/Utility/FilteredIterator.php
WordPress 5.5.2 included a security fix to disable deserialization in `Requests_Utility_FilteredIterator`:
https://core.trac.wordpress.org/changeset/49373
This PR aims to merge that change upstream.
=> Disable deserialization in FilteredIterator

library/Requests.php, library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php, tests/Transport/Base.php
The majority of comparisons use "human readable" compare order. This fixes the few which used Yoda conditions.
=> CS: remove Yoda conditions

library/Requests.php, tests/Transport/Base.php
This fixes an issue on PHP < 7.0, where the value of `Requests_Response::$body` could be `false` when there was no response body.
The behaviour of the `substr()` method has seen some (undocumented) changes across PHP versions.
In PHP < 7.0, the method would return `false` if `$start` was equal to the length of the subject string.
As of PHP 7.0, the method will return an empty string in that case and only return `false` if `$start` is _beyond_ the length of the subject string.
In PHP 8.0, this will change yet again and the function will no longer return `false` ever, but will return an empty string in all "failure" cases.
Knowing this, checking the return value of `substr()` with `empty()` is the most appropriate course of action.
I've verified that this is the only place in the …
=> Requests::parse_response(): ensure `body` is always a string

library/Requests/Utility/FilteredIterator.php, tests/Utility/FilteredIterator.php
Clean up the newly introduced code.
* Use an unique class name for the test class.
* Use camelCase method names for the tests.
* Add method visibility modifiers
* Remove unnecessary whitelist comments.
* Fix up whitespace.
=> CS: clean up after merges

tests/Auth/Basic.php, tests/ChunkedEncoding.php, tests/Cookies.php, tests/Encoding.php, tests/IDNAEncoder.php, tests/IRI.php, tests/Proxy/HTTP.php, tests/Requests.php, tests/Response/Headers.php, tests/Session.php, tests/Transport/Base.php
This is a long established best practice.
PHPUnit contains a variety of assertions and the ones available has been extended hugely over the years.
To have the most reliable tests, the most specific assertion should be used.
Refs:
* https://phpunit.de/manual/4.8/en/appendixes.assertions.html
* https://phpunit.readthedocs.io/en/7.5/assertions.html#
Most notably, this changes nearly all calls to `assertEquals()` to `assertSame()`, where `assertEquals()` does a loose type comparison and `assertSame()` does a strict type comparison.
Refs:
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertEquals
* https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertSame
---- 
Note: this change now causes two tests to fail on PHP 5.4-5.6 …
=> QA: use the most specific PHPUnit assertion possible

library/Requests.php, tests/Session.php
This fixes an issue on PHP 5.2/5.3 where the `Requests_Response::__toString()` method would not always automagically be invoked.
I've verified that this is the only place in the application where the `Requests_Response::$url` property is being set.
I considered making the property `private` and adding magic setter/getter methods, but that would open the class up to injection of other non-public properties, which is not the intention of this change.
Includes:
* Making the tests which cover this property use a strict typed assertion.
* Adding "failure messages" to the various assertions in this test to more easily be able to distinguish which assertion has failed.
=> Requests::parse_response(): ensure URL is always a string

.gitattributes, .gitignore, .phpcs.xml.dist, .travis.yml, composer.json, library/Requests.php, library/Requests/IDNAEncoder.php, library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php, tests/Cookies.php, tests/Utility/FilteredIterator.php
This PR:
* Adds `dev` requirements for the WP Coding Standards, PHPCompatibility and the DealerDirect Composer PHPCS plugin.
* Adds a custom PHPCS ruleset which uses the `WordPress-Extra` ruleset to check the code style and code quality of code in this repo and the `PHPCompatibility` standard to test for PHP cross-version compatibility.
* Adds convenience scripts to the `composer.json` file to check the code of the repo.
* Allows for individual developers to overload the `.phpcs.xml.dist` file by ignoring the typical overload files.
* Adds the CS check to the Travis script in a separate stage.
The CS check only needs to be run on one build, preferably against a high PHP version.
To that end, I've set up stages and added the CS check to a separate `stage`.
Ref: …
=> CI/QA: add code style check

.travis.yml, composer.json, tests/Transport/Base.php, tests/phpunit.xml.dist
Slightly simpler alternative for #428 to allow the tests to run on PHP 8 for now (save for two tests).
Based on this set up, we can conclude that for the code covered by the current tests, the library is compatible with PHP 8.
Closes #428 
/cc @TimothyBJacobs
The PHPUnit configuration did not validate against any available PHPUnit XSD file.
This stabilizes the file and annotates against which XSD it has been validated.
Notes:
* The default value of the `backupGlobals` option has changed in PHPUnit 6 from `true` to `false`.
Setting this explicitly to `true` for cross-version compatibility.
* The file will now validate against the PHPUnit XSD for PHPUnit 4.4 up to 9.2.
These two tests set exception expectations in a limited set of circumstances. In all other circumstances they basically …
=> Run tests against  PHP 8

README.md, docs/why-requests.md
Fixes #440.
Replace where relevant the occurrences of "https://github.com/rmccue/Requests/" in the documentation
=>  Replace where relevant the occurrences of "https://github.com/rmccue/Requests/"

tests/utils/proxy/start.sh, tests/utils/proxy/stop.sh
Without proper shebangs in the shell script, some systems assume lowest common denominator of `sh` for compatibility reasons.
This breaks with the testing logic in the current scripts:
This PR adds a shebang to the scripts to use `bash` as the executable shell instead.
=> Add shebangs to proxy shell scripts

library/Requests/Transport/cURL.php, tests/Transport/Base.php
Fixes #432
This prevents the fatal `TypeError` on PHP 8.0 and maintains the existing behaviour as it was on previous PHP versions.
Includes dedicated test. The test will pass on PHP < 8 and fail on PHP 8 without this fix and pass on all supported PHP versions with the fix.
=> Requests_Transport_cURL - fix PHP 8.0 issue with filename verification

library/Requests/Utility/FilteredIterator.php, tests/Utility/FilteredIterator.php, tests/phpunit.xml.dist
The `$callback` passed to the constructor of the `FilteredIterator` class may not be callable and if so, would cause a fatal error.
This puts some defensive coding in place to guard against that and adds a unit test for it as well.
This also fixes the tests failing on PHP 5.2, as when the object is unserialized on PHP 5.2, the `$callback` property will no longer be set. This looks to have been a bug in PHP 5.2 which was fixed in PHP 5.3.
Even though the code is wrapped in a version check for running, the code still needs to parse correctly on low PHP versions.
This was not the case now, which could break the running of the tests of PHP 5.3.
Fixed now.
As all tests are explicitly named in the test configuration, the  test for the `FilteredIterator` as added in #422 were not being run as …
=> FilteredIterator: fix PHP 5.2/5.3 compatibility and actually run the tests

.codecov.yml, .coveralls.yml
This commit:
* Removes the configuration for the Coverall service which is no longer used.
* Adds a configuration for the CodeCov service (which _is_ used).
This configuration:
- Adds a threshold of a 1% difference before failing the build for project status checks (= total coverage for the whole project).
Too often, due to some imprecision in how the code coverage is calculated, a difference of `-0.12%` (or similar) will be reported.
That kind of difference is no a reason to fail the build and block merges as it is often incorrect anyhow. (how can a docs PR cause a negative code coverage diff ?)
- Explicitly sets the path for which files we expect to be covered.
- For patch status checks the threshold remains at 0% (which is the default), meaning that the code coverage is not allowed to …
=> CodeCov: add configuration

.travis.yml
Follow up on #439
Even though we'll soon be moving to GH Actions, I think it is important to fix the failing build on PHP 8.0 ahead of this and ahead of the 1.8.0 release, as otherwise any badges in the README, on Packagist and on the website, will show the CI build as failing until we release version 2.0.0 and that wouldn't be right.
=> Travis: fix PHP 8.0 build

README.md
The homepage of the https://requests.ryanmccue.info/ website is automatically generated from the `readme` file.
The last time the site was generated was in 2016. Since then a lot has changed in GH Pages and a lot of the [dependencies](https://pages.github.com/versions/) used to generate a site have been updated to newer releases.
Most notable, the kramdown engine has moved from v1 to v2 which has implications for how code blocks are shown on the website.
For the best results, it is strongly recommended to not use "whitespace" marked code blocks, but to use code block fencing with a language indicator to enable syntax highlighting as well.
This commit fixes up the `README` file in anticipation of the release.
=> README: fix code blocks

.codecov.yml, .gitattributes, .github/workflows/cs.yml, .github/workflows/lint.yml, .github/workflows/quicktest.yml, .github/workflows/test.yml, .travis.yml, README.md, composer.json, tests/Proxy/HTTP.php, tests/utils/proxy/start.sh, tests/utils/proxy/stop.sh
Depends on: PRs #458 (and by extension PR #457) and #464.
Those PRs will need to be merged before this PR can become mergable.
Supersedes: PRs #447 and #461
Closes #447
Closes #461
This PR moves the CI checks for PHP 5.5 - current to GH Actions, while leaving the CI checks against PHP 5.2 - 5.4 to be run via Travis. This allows for this move to be done _now_ while PHP 5.2 - 5.4 are still supported and will still safeguard (via Travis) that the code is still compatible with PHP 5.2 - 5.4.
This PR incorporates the work previously done by @schlessera in #447 and builds on that.
**Background of why the PHP 5.2-5.4 builds won't be able to move to GH Actions:**
The code of the test-server used during the running of the unit tests requires PHP 5.5 minimum due to the use of `yield`.
On Travis, it …
=> CI: switch to GitHub Actions for PHP 5.5 - current

library/Requests/Transport/cURL.php, tests/Transport/cURL.php
Fixes #453 
This PR was originally authored by @carlalexander, and I only recreate it here because I messed up the original PR found at #454 .
=> Manage "Expect" header with cURL transport

README.md, docs/authentication-custom.md, docs/authentication.md, docs/goals.md, docs/hooks.md, docs/proxy.md, docs/usage-advanced.md, docs/usage.md, docs/why-requests.md
The "Documentation" section of the https://requests.ryanmccue.info/ website is automatically generated from the files in the `docs` folder.
The last time the site was generated was in 2016. Since then a lot has changed in GH Pages and a lot of the [dependencies](https://pages.github.com/versions/) used to generate a site have been updated to newer releases.
This commit makes various tweaks to the markdown for improved rendering on the current GH Pages setup.
While going through the pages, I've also done a cursory review of the content and fixed up information which was extremely outdated or plain incorrect by now.
Includes:
* Use spaces not tabs for indentation in markdown files.
* Fixing up various URLs/links.
* Removal of various uses of ableist language.
* Punctuation fixes.
=> Docs: update content and various tweaks to the markdown

api/class-Requests_Exception.html, docs/authentication-custom.md, docs/authentication.md, docs/goals.md, docs/hooks.md, docs/index.md, docs/proxy.md, docs/usage-advanced.md, docs/usage.md, docs/why-requests.md, download/index.md, index.md, support/index.md
... after site review of the regenerated website by @schlessera and me.
Follow up to #468
Sister-PR to #477
👉  To be merged after PR #477 has been merged and the 1.8.0 release has gone out.
=> GH Pages: various minor tweaks to the content

.gitattributes
There are a handful of repository specific config and info files still downloaded with a fresh `composer install` of this package, these are now ignored
=> Add misc. files to gitattributes

.gitattributes, library/Requests.php
Oops.. looks like we forgot something for the release. Only just noticed it when I checked the file diff for the WP Core patch.
As the version constant is generally used to verify the version for using certain features of a package, does this warrant a `1.8.1` release ?
And if so, should I update the version number to `1.8.1` in this PR ?
=> Requests::Version: update version number

CHANGELOG.md
Covering all PRs merged in the milestone: https://github.com/WordPress/Requests/milestone/4
PR for tracking changes for the 1.8.1 release. Target release date: **Friday June 4 2021**.
Make sure to copy the links to the issues and the links to the GH usernames from the bottom of the changelog!
=> Changelog for release 1.8.1

library/Requests/Transport/cURL.php, library/Requests/Transport/fsockopen.php, tests/Transport/BaseTestCase.php
Throw an exception if an invalid path is provided in the filename option.
Before this change, the script will continue and try to write and close a file pointer which does not exist.
=> Throw exception if invalid filename is provided

library/Requests/Transport/cURL.php
Hey,
as stated in the curl docs https://everything.curl.dev/libcurl-http/requests#referrer
the Referer is a header that tells the server from which URL the user-agent was directed from.
So imho this shouldn't be the request's target url.
=> Removed CURLOPT_REFERER
